set alignment bug's depends
openshift-eng/doozer pull request #814
Opened 2023-08-04 09:11 UTC by Ximinhan

re: [ART-7462](https://issues.redhat.com/browse/ART-7462)
accoring to https://github.com/openshift/cluster-update-keys/pull/47#issuecomment-1664730578
after creating an alignment bug CI will check if it has a bug to depend on if it's not non-GA version
we need to check if a similar bug in higher version exist and try to link it

2023-08-04 09:16 UTC, Ximinhan commented
I guess CI's check is to make sure it is backported from a higher version, but our pr and bug maybe not need to strictly follow the convention

2023-08-11 06:52 UTC, joepvd requested changes
Maybe setting the valid-bug label is enough? 
Bug titles are changing here: https://github.com/openshift-eng/doozer/pull/818

2023-08-11 07:40 UTC, Ximinhan commented
> 

no, the label will be refreshed by the next CI validate check run

2023-08-14 05:31 UTC, Ximinhan commented
replaced by https://github.com/openshift-eng/art-tools/pull/12

2023-08-14 05:31 UTC, closed without merging